name: tmdb_dart
version: 0.0.1
description: >-
  API client for TheMovieDB 
environment:
  sdk: '>=2.0.0-dev <3.0.0'
author: Marian Bejenari <kerego@outlook.com>
homepage: https://github.com/Kerego/dart_tmdb
dependencies:
  http: 0.11.3+17